on:
  push:
    branches:
      - main

name: release-please

jobs:
  release-please:
    if: github.repository_owner == 'varfish-org'
    runs-on: ubuntu-latest
    steps:
      - name: Run release-please
        uses: GoogleCloudPlatform/release-please-action@v4
        id: release
        with:
          release-type: simple
          token: ${{ secrets.BOT_TOKEN }}
